% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 1/Entire Image/reg_KSpot1_MM', [467,469,203,147], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 1/Positive/reg_KSpot1_MM_pos', [49,79,203,147], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 1/Negative/reg_KSpot1_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 2/Entire Image/reg_KSpot2_MM', [565,241,121,104], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 2/Positive/reg_KSpot2_MM_pos', [69,394,121,104], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 2/Negative/reg_KSpot2_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 3/Entire Image/reg_KSpot3_MM', [335,129,317,395], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 3/Positive/reg_KSpot3_MM_pos', [3,579,317,395], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 3/Negative/reg_KSpot3_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 4/Entire Image/reg_KSpot4_MM', [338,326,276,201], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 4/Positive/reg_KSpot4_MM_pos', [527,665,276,201], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 4/Negative/reg_KSpot4_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 5/Entire Image/reg_KSpot5_MM', [533,249,269,115], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 5/Positive/reg_KSpot5_MM_pos', [551,699,269,115], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 5/Negative/reg_KSpot5_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 6/Entire Image/reg_KSpot6_MM', [553,404,150,261], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 6/Positive/reg_KSpot6_MM_pos', [32,109,150,261], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 6/Negative/reg_KSpot6_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 7/Entire Image/reg_KSpot7_MM', [579,231,189,279], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 7/Positive/reg_KSpot7_MM_pos', [109,575,189,279], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 7/Negative/reg_KSpot7_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 8/Entire Image/reg_KSpot8_MM', [263,239,255,517], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 8/Positive/reg_KSpot8_MM_pos', [677,237,255,517], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 8/Negative/reg_KSpot8_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 9/Entire Image/reg_KSpot9_MM', [495,224,161,165], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 9/Positive/reg_KSpot9_MM_pos', [136,692,161,165], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 9/Negative/reg_KSpot9_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 10/Entire Image/reg_KSpot10_MM', [598,226,141,135], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 10/Positive/reg_KSpot10_MM_pos', [141,670,141,135], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 1 Spot 10/Negative/reg_KSpot10_MM_neg');
% 
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 11/Entire Image/reg_KSpot11_MM', [462,375,144,66], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 11/Positive/reg_KSpot11_MM_pos', [100,87,144,66], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 11/Negative/reg_KSpot11_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 12/Entire Image/reg_KSpot12_MM', [644,247,324,179], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 12/Positive/reg_KSpot12_MM_pos', [356,716,324,179], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 12/Negative/reg_KSpot12_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 13/Entire Image/reg_KSpot13_MM', [718,300,242,188], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 13/Positive/reg_KSpot13_MM_pos', [162,599,242,188], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 13/Negative/reg_KSpot13_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 14/Entire Image/reg_KSpot14_MM', [666,428,202,161], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 14/Positive/reg_KSpot14_MM_pos', [131,158,202,161], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 14/Negative/reg_KSpot14_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 15/Entire Image/reg_KSpot15_MM', [732,504,90,143], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 15/Positive/reg_KSpot15_MM_pos', [97,162,90,143], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 15/Negative/reg_KSpot15_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 16/Entire Image/reg_KSpot16_MM', [610,359,144,136], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 16/Positive/reg_KSpot16_MM_pos', [55,63,144,136], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 16/Negative/reg_KSpot16_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 17/Entire Image/reg_KSpot17_MM', [551,323,138,138], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 17/Positive/reg_KSpot17_MM_pos', [52,676,138,138], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 2 Spot 17/Negative/reg_KSpot17_MM_neg');
% 
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 18/Entire Image/reg_KSpot18_MM', [394,509,67,75], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 18/Positive/reg_KSpot18_MM_pos', [849,46,67,75], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 18/Negative/reg_KSpot18_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 19/Entire Image/reg_KSpot19_MM', [519,392,111,174], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 19/Positive/reg_KSpot19_MM_pos', [45,60,111,174], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 19/Negative/reg_KSpot19_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 20/Entire Image/reg_KSpot20_MM', [317,283,275,207], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 20/Positive/reg_KSpot20_MM_pos', [97,697,275,207], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 20/Negative/reg_KSpot20_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 21/Entire Image/reg_KSpot21_MM', [511,387,227,185], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 21/Positive/reg_KSpot21_MM_pos', [69,693,227,185], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 21/Negative/reg_KSpot21_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 22/Entire Image/reg_KSpot22_MM', [244,174,180,127], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 22/Positive/reg_KSpot22_MM_pos', [85,718,180,127], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 22/Negative/reg_KSpot22_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 23/Entire Image/reg_KSpot23_MM', [555,249,202,97], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 23/Positive/reg_KSpot23_MM_pos', [87,644,202,97], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 3 Spot 23/Negative/reg_KSpot23_MM_neg');
% 
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 25/Entire Image/reg_KSpot25_MM', [361,418,262,112], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 25/Positive/reg_KSpot25_MM_pos', [652,29,262,112], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 25/Negative/reg_KSpot25_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 26/Entire Image/reg_KSpot26_MM', [362,373,128,99], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 26/Positive/reg_KSpot26_MM_pos', [153,713,128,99], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 26/Negative/reg_KSpot26_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 27/Entire Image/reg_KSpot27_MM', [614,295,114,167], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 27/Positive/reg_KSpot27_MM_pos', [36,179,114,167], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 27/Negative/reg_KSpot27_MM_neg');
% crop_images_to_neg_and_pos('../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 28/Entire Image/reg_KSpot28_MM', [697,406,170,137], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 28/Positive/reg_KSpot28_MM_pos', [23,24,170,137], '../../Dog Analysis/Samples to Run/Kurt Left Eye/Location 4 Spot 28/Negative/reg_KSpot28_MM_neg');

% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 1\Entire Image\reg_loc1_spot1_ChrisL_MM', [717,337,191,315], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 1\Positive\reg_loc1_spot1_ChrisL_MM_pos', [63,27,191,315], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 1\Negative\reg_loc1_spot1_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 2\Entire Image\reg_loc1_spot2_ChrisL_MM', [311,305,175,223], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 2\Positive\reg_loc1_spot2_ChrisL_MM_pos', [670,623,175,223], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 2\Negative\reg_loc1_spot2_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 3\Entire Image\reg_loc1_spot3_ChrisL_MM', [138,149,60,58], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 3\Positive\reg_loc1_spot3_ChrisL_MM_pos', [701,116,60,58], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 3\Negative\reg_loc1_spot3_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 4\Entire Image\reg_loc1_spot4_ChrisL_MM', [352,72,38,61], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 4\Positive\reg_loc1_spot4_ChrisL_MM_pos', [774,112,38,61], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 4\Negative\reg_loc1_spot4_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 5\Entire Image\reg_loc1_spot5_ChrisL_MM', [749,419,176,310], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 5\Positive\reg_loc1_spot5_ChrisL_MM_pos', [42,132,176,310], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 1 Spot 5\Negative\reg_loc1_spot5_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 6/Entire Image/reg_loc2_spot6_ChrisL_MM', [597,628,54,44], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 6\Positive\reg_loc2_spot6_ChrisL_MM_pos', [89,52,54,44], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 6\Negative\reg_loc2_spot6_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 7\Entire Image\reg_loc2_spot7_ChrisL_MM', [747,336,169,189], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 7\Positive\reg_loc2_spot7_ChrisL_MM_pos', [71,61,169,189], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 7\Negative\reg_loc2_spot7_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 8\Entire Image\reg_loc2_spot8_ChrisL_MM', [603,460,39,57], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 8\Positive\reg_loc2_spot8_ChrisL_MM_pos', [64,71,39,57], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 8\Negative\reg_loc2_spot8_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 9\Entire Image\reg_loc2_spot9_ChrisL_MM', [698,290,44,56], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 9\Positive\reg_loc2_spot9_ChrisL_MM_pos', [68,103,44,56], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 9\Negative\reg_loc2_spot9_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 10\Entire Image\reg_loc2_spot10_ChrisL_MM', [513,403,257,209], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 10\Positive\reg_loc2_spot10_ChrisL_MM_pos', [41,49,257,209], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 2 Spot 10\Negative\reg_loc2_spot10_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 3 Spot 11\Entire Image\reg_loc3_spot11_ChrisL_MM', [655,195,96,101], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 3 Spot 11\Positive\reg_loc3_spot11_ChrisL_MM_pos', [80,127,96,101], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 3 Spot 11\Negative\reg_loc3_spot11_ChrisL_MM_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Chris Left Eye/Location 3 Spot 12\Entire Image\reg_loc3_spot12_ChrisL_MM', [211,395,169,173], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 3 Spot 12\Positive\reg_loc3_spot12_ChrisL_MM_pos', [683,73,169,173], '../../Primed Data Sets/Dogs/Chris Left Eye/Location 3 Spot 12\Negative\reg_loc3_spot12_ChrisL_MM_neg');

% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Dave Left Eye/Location 1 Spot 2/Entire Image/reg_loc1_spot2_DaveL_MM', [873,388,34,23], '../../../Primed Data Sets/Dogs/Dave Left Eye/Location 1 Spot 2/Positive/reg_loc1_spot2_DaveL_MM_pos', [259,192,34,23], '../../../Primed Data Sets/Dogs/Dave Left Eye/Location 1 Spot 2/Negative/reg_loc1_spot2_DaveL_MM_neg');

% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Camille Left Eye/Spot 2/Entire Image/reg_1location_CamilleL_Spot2', [320,593,116,79], '../../Primed Data Sets/Dogs/Camille Left Eye/Spot 2/Positive/reg_1location_CamilleL_Spot2_pos', [82,65,116,79], '../../Primed Data Sets/Dogs/Camille Left Eye/Spot 2/Negative/reg_1location_CamilleL_Spot2_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Camille Left Eye/Spot 3/Entire Image/reg_1location_CamilleL_Spot3', [156,248,440,466], '../../Primed Data Sets/Dogs/Camille Left Eye/Spot 3/Positive/reg_1location_CamilleL_Spot3_pos', [663,13,320,256], '../../Primed Data Sets/Dogs/Camille Left Eye/Spot 3/Negative/reg_1location_CamilleL_Spot3_neg');
% crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Camille Left Eye/Spot 4/Entire Image/reg_1location_CamilleL_Spot4', [707,485,255,192], '../../Primed Data Sets/Dogs/Camille Left Eye/Spot 4/Positive/reg_1location_CamilleL_Spot4_pos', [54,68,255,192], '../../Primed Data Sets/Dogs/Camille Left Eye/Spot 4/Negative/reg_1location_CamilleL_Spot4_neg');
crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Camille Left Eye/Spot 5/Entire Image/reg_2location_CamilleL_Spot5', [516,463,141,104], '../../Primed Data Sets/Dogs/Camille Left Eye/Spot 5/Positive/reg_2location_CamilleL_Spot5_pos', [42,57,141,104], '../../Primed Data Sets/Dogs/Camille Left Eye/Spot 5/Negative/reg_2location_CamilleL_Spot5_neg');
crop_images_to_neg_and_pos('../../Primed Data Sets/Dogs/Camille Left Eye/Spot 6/Entire Image/reg_2location_CamilleL_Spot6', [504,363,237,226], '../../Primed Data Sets/Dogs/Camille Left Eye/Spot 6/Positive/reg_2location_CamilleL_Spot6_pos', [20,148,237,226], '../../Primed Data Sets/Dogs/Camille Left Eye/Spot 6/Negative/reg_2location_CamilleL_Spot6_neg');