classdef MetricGroupTypes
    % MetricGroupTypes
    
    properties
        displayString
        dirName
        filenameTag
        explanationString
    end
    
    enumeration
        Diattenuation (...
            'Diattenuation',...
            'Diattenuation',...
            'D',...
            'Contains all metrics that are determined from the diattenuation matrix found through the Lu-Chipman decomposition.');
        
        Polarizance (...
            'Polarizance',...
            'Polarizance',...
            'P',...
            'Contains all metrics that are determined from the polarizance matrix found through the Lu-Chipman decomposition.');
            
        Retardance (...
            'Retardance',...
            'Retardance',...
            'R',...
            'Contains all metrics that are determined from the retardance matrix found through the Lu-Chipman decomposition.');
        
        GeneralMetrics (...
            'General Metrics',...
            'General Metrics',...
            '',...
            'Contains the metrics that are determined from the all of the Mueller Matrix entries, instead of just select indices. In particular, the Degree of Polarization, Depolarization Index, and Q Metric are found here.');
        
        AdditionalRetardanceMetrics (...
            'Additional Retardance Metrics',...
            'More Retardance Metrics',...
            '',...
            'Contains additional retardance metrics that use the elements from the retardance matrix, but are not the standard set found in the Retardance directory.');
        
        Stats (...
            'Statistics',...
            'Stats',...
            '',...
            'Contains some basic statistics of the metrics computed');
       
        Anisotropy (...
            'Anisotropy',...
            'Anisotropy',...
            '',...
            'Contains anisotropic parameters that use the elements from the total matrix and the calculated metrics values.');
    end
    
    methods
        function enum = MetricGroupTypes(displayString, dirName, filenameTag, explanationString)
            enum.displayString = displayString;
            enum.dirName = dirName;
            enum.filenameTag = filenameTag;
            enum.explanationString = explanationString;
        end
    end
    
end

