classdef MetricTypes
    % MetricTypes
    
    properties
        displayString
        metricGroupType
        filenameTag
        dataRange
    end
    
    enumeration
        % ** DIATTENUATION GROUP **
        Diattenuation (...
            'Diattenuation',...
            MetricGroupTypes.Diattenuation,...
            '',...
            [0,1]);
        
        Diattenuation_Horizontal (...
            'Diattenuation - Horizontal',...
            MetricGroupTypes.Diattenuation,...
            'Horz',...
            [-1,1]);
        
        Diattenuation_45deg (...
            'Diattenuation - 45°',...
            MetricGroupTypes.Diattenuation,...
            '45°',...
            [-1,1]);
        
        Diattenuation_Circular (...
            'Diattenuation - Circular',...
            MetricGroupTypes.Diattenuation,...
            'Circ',...
            [-1,1]);
        
        Diattenuation_Linear (...
            'Diattenuation - Linear',...
            MetricGroupTypes.Diattenuation,...
            'Lin',...
            [0,1]);
        
        % ** POLARIZANCE GROUP **
        Polarizance (...
            'Polarizance',...
            MetricGroupTypes.Polarizance,...
            '',...
            [0,1]);
        
        Polarizance_Horizontal (...
            'Polarizance - Horizontal',...
            MetricGroupTypes.Polarizance,...
            'Horz',...
            [-1,1]);
        
        Polarizance_45deg (...
            'Polarizance - 45°',...
            MetricGroupTypes.Polarizance,...
            '45°',...
            [-1,1]);
        
        Polarizance_Circular (...
            'Polarizance - Circular',...
            MetricGroupTypes.Polarizance,...
            'Circ',...
            [-1,1]);
        
        Polarizance_Linear (...
            'Polarizance - Linear',...
            MetricGroupTypes.Polarizance,...
            'Lin',...
            [0,1]);
        
        % ** RETARDANCE GROUP **
        Retardance (...
            'Retardance',...
            MetricGroupTypes.Retardance,...
            '',...
            [0,180]);
        
        Retardance_Horizontal (...
            'Retardance - Horizontal',...
            MetricGroupTypes.Retardance,...
            'Horz',...
            [-180,180]);
        
        Retardance_45deg (...
            'Retardance - 45°',...
            MetricGroupTypes.Retardance,...
            '45°',...
            [-180,180]);
        
        Retardance_Circular (...
            'Retardance - Circular',...
            MetricGroupTypes.Retardance,...
            'Circ',...
            [-180,180]);
        
        Retardance_Linear (...
            'Retardance - Linear',...
            MetricGroupTypes.Retardance,...
            'Lin',...
            [0,180]);
        
        % ** GENERAL METRIC GROUP **
        DegreeOfPolarization (...
            'Degree of Polarization',...
            MetricGroupTypes.GeneralMetrics,...
            'DOP',...
            [0,1]);
        
        DepolarizationIndex (...
            'Depolarization Index',...
            MetricGroupTypes.GeneralMetrics,...
            'DI',...
            [0,1]);
        
        QMetric (...
            'Q Metric',...
            MetricGroupTypes.GeneralMetrics,...
            'Q',...
            [0,3]);
        
        % ** ADDITIONAL RETARDANCE METRICS **
        OpticalRotation (...
            'Optical Rotation',...
            MetricGroupTypes.AdditionalRetardanceMetrics,...
            'OR',...
            [-180,180]);
        
        Delta (...
            'Delta',...
            MetricGroupTypes.AdditionalRetardanceMetrics,...
            'Delta',...
            [0,180]);
        
        Rho1 (...
            'Rho 1',...
            MetricGroupTypes.AdditionalRetardanceMetrics,...
            'Rho1',...
            [0,90]);
        
        Rho2 (...
            'Rho 2',...
            MetricGroupTypes.AdditionalRetardanceMetrics,...
            'Rho2',...
            [-90,90]);
        
        Theta (...
            'Theta',...
            MetricGroupTypes.AdditionalRetardanceMetrics,...
            'Theta',...
            [-90,90]);
    end
    
    methods
        function enum = MetricTypes(displayString, metricGroupType, filenameTag, dataRange)
            enum.displayString = displayString;
            enum.metricGroupType = metricGroupType;
            enum.filenameTag = filenameTag;
            enum.dataRange = dataRange;
        end
    end
    
end

