classdef MetricTypes
    % MetricTypes
    
    properties
        displayString
        metricGroupType
        filenameTag
    end
    
    enumeration
        % ** DIATTENUATION GROUP **
        Diattenuation (...
            'Diattenuation',...
            MetricGroupTypes.Diattenuation,...
            '');
        
        Diattenuation_Horizontal (...
            'Diattenuation - Horizontal',...
            MetricGroupTypes.Diattenuation,...
            'Horz');
        
        Diattenuation_45deg (...
            'Diattenuation - 45°',...
            MetricGroupTypes.Diattenuation,...
            '45°');
        
        Diattenuation_Circular (...
            'Diattenuation - Circular',...
            MetricGroupTypes.Diattenuation,...
            'Circ');
        
        Diattenuation_Linear (...
            'Diattenuation - Linear',...
            MetricGroupTypes.Diattenuation,...
            'Lin');
        
        % ** POLARIZANCE GROUP **
        Polarizance (...
            'Polarizance',...
            MetricGroupTypes.Polarizance,...
            '');
        
        Polarizance_Horizontal (...
            'Polarizance - Horizontal',...
            MetricGroupTypes.Polarizance,...
            'Horz');
        
        Polarizance_45deg (...
            'Polarizance - 45°',...
            MetricGroupTypes.Polarizance,...
            '45°');
        
        Polarizance_Circular (...
            'Polarizance - Circular',...
            MetricGroupTypes.Polarizance,...
            'Circ');
        
        Polarizance_Linear (...
            'Polarizance - Linear',...
            MetricGroupTypes.Polarizance,...
            'Lin');
        
        % ** RETARDANCE GROUP **
        Retardance (...
            'Retardance',...
            MetricGroupTypes.Retardance,...
            '');
        
        Retardance_Horizontal (...
            'Retardance - Horizontal',...
            MetricGroupTypes.Retardance,...
            'Horz');
        
        Retardance_45deg (...
            'Retardance - 45°',...
            MetricGroupTypes.Retardance,...
            '45°');
        
        Retardance_Circular (...
            'Retardance - Circular',...
            MetricGroupTypes.Retardance,...
            'Circ');
        
        Retardance_Linear (...
            'Retardance - Linear',...
            MetricGroupTypes.Retardance,...
            'Lin');
        
        % ** GENERAL METRIC GROUP **
        DegreeOfPolarization (...
            'Degree of Polarization',...
            MetricGroupTypes.GeneralMetrics,...
            'DOP');
        
        DepolarizationIndex (...
            'Depolarization Index',...
            MetricGroupTypes.GeneralMetrics,...
            'DI');
        
        QMetric (...
            'Q Metric',...
            MetricGroupTypes.GeneralMetrics,...
            'Q');
        
        % ** ADDITIONAL RETARDANCE METRICS **
        OpticalRotation (...
            'Optical Rotation',...
            MetricGroupTypes.AdditionalRetardanceMetrics,...
            'OR');
        
        Delta (...
            'Delta',...
            MetricGroupTypes.AdditionalRetardanceMetrics,...
            'Delta');
        
        Rho1 (...
            'Rho 1',...
            MetricGroupTypes.AdditionalRetardanceMetrics,...
            'Rho1');
        
        Rho2 (...
            'Rho 2',...
            MetricGroupTypes.AdditionalRetardanceMetrics,...
            'Rho2');
        
        Theta (...
            'Theta',...
            MetricGroupTypes.AdditionalRetardanceMetrics,...
            'Theta');
    end
    
    methods
        function enum = MuellerMatrixComputationTypes(displayString, explanationString, startDateString, endDateString)
            enum.displayString = displayString;
            enum.explanationString = explanationString;
            enum.startDateString = startDateString;
            enum.endDateString = endDateString;
        end
    end
    
end

